name: workflow commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon."
      - name: test 1
        run: echo "::error title=Testje,file=app.js,line=1,endLine=1,col=2,endColumn=4::Missing testje"
      - name: test 2
        run: echo "::debug title=Testje,file=app.js,line=1,endLine=1,col=2,endColumn=4::Missing testje"
      - name: test 3
        run: echo "::warning title=Testje,file=app.js,line=1,endLine=1,col=2,endColumn=4::Missing testje"
      - name: test 4
        run: echo "::notice title=Testje,file=app.js,line=1,endLine=1,col=2,endColumn=4::Missing testje"
      - name: Group of logs
        run: |
          echo "::group::My group test"
          echo "Inside group"
          echo "::endgroup::"
      - name: Mask string
        run: echo "::add-mask::Hidden string"
      - name: Echo secret string
        run: Echo "secret string"